import { useState, useEffect } from 'react';
import {
  projectAuth,
  projectStorage,
  projectFirestore,
} from '../firebase/config';
import { useAuthContext } from './useAuthContext';

export const useSignup = () => {
  const [isCancelled, setIsCancelled] = useState(false);
  const [error, setError] = useState(null);
  const [isPending, setIsPending] = useState(false);
  const { dispatch } = useAuthContext();

  const signup = async (email, password, displayName, thumbnail) => {
    setError(null);
    setIsPending(true);

    try {
      // signup
      const res = await projectAuth.createUserWithEmailAndPassword(
        email,
        password
      );

      if (!res) {
        throw new Error('Could not complete signup');
      }

      // upload user thumbnail
      // every user will have their own folder with their thumbnail uploaded
      const uploadPath = `thumbnails/${res.user.uid}/${thumbnail.name}`;
      const storageRef = projectStorage.ref();
      const img = await storageRef.child(uploadPath).put(thumbnail);
      const imgUrl = await img.ref.getDownloadURL();

      // add display name and thumbnail to user
      await res.user.updateProfile({ displayName, photoURL: imgUrl });

      // create user document to access all users data later
      // use user uid (instead the autogenerated) to create a synergy between the auth user and the doc user
      await projectFirestore.collection('users').doc(res.user.uid).set({
        online: true,
        displayName,
        photoURL: imgUrl,
      });

      // dispatch login action
      dispatch({ type: 'LOGIN', payload: res.user });

      if (!isCancelled) {
        setIsPending(false);
        setError(null);
      }
    } catch (err) {
      if (!isCancelled) {
        setError(err.message);
        setIsPending(false);
      }
    }
  };

  useEffect(() => {
    return () => setIsCancelled(true);
  }, []);

  return { signup, error, isPending };
};
